name: SonarQube Scan

on:
  push:
    branches:
      - main  # Update with your branch name

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Update Python version if needed

      # Run your tests here if necessary

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://your_sonarqube_server_url \
            -Dsonar.login=your_sonarqube_token

        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
